### ISSUE TITLE
Running the tests

### ISSUE THREAD

**Issue by oskbor** [eric-taix/neo4dart#1]
Hi,
this looks like a nice beginning for a dart Neo4j driver. I checked out the project and tried to run the tests, but there is some issues with the hard coded ids in the tests.

I get this output:

```
[2014-03-06 12:58:15.137] DEBUG http: R0: get data on http://127.0.0.1:7474/db/data with body 
[2014-03-06 12:58:15.329] DEBUG http: R0: Received data in 203ms with status 200: [{
  "extensions" : {
  },
  "node" : "http://127.0.0.1:7474/db/data/node",
  "node_index" : "http://127.0.0.1:7474/db/data/index/node",
  "relationship_index" : "http://127.0.0.1:7474/db/data/index/relationship",
  "extensions_info" : "http://127.0.0.1:7474/db/data/ext",
  "relationship_types" : "http://127.0.0.1:7474/db/data/relationship/types",
  "batch" : "http://127.0.0.1:7474/db/data/batch",
  "cypher" : "http://127.0.0.1:7474/db/data/cypher",
  "indexes" : "http://127.0.0.1:7474/db/data/schema/index",
  "constraints" : "http://127.0.0.1:7474/db/data/schema/constraint",
  "transaction" : "http://127.0.0.1:7474/db/data/transaction",
  "node_labels" : "http://127.0.0.1:7474/db/data/labels",
  "neo4j_version" : "2.0.1"
}]
unittest-suite-wait-for-done
[2014-03-06 12:58:15.385] DEBUG http: R1: POST data on http://127.0.0.1:7474/db/data/node with body {"firstname":"eric","name":"taix"}
[2014-03-06 12:58:15.398] DEBUG http: R2: POST data on http://127.0.0.1:7474/db/data/node with body {"firstname":"eric","name":"taix"}
[2014-03-06 12:58:15.398] DEBUG http: R3: POST data on http://127.0.0.1:7474/db/data/node with body {"firstname":"eric2","name":"taix2"}
[2014-03-06 12:58:15.401] DEBUG http: R4: POST data on http://127.0.0.1:7474/db/data/node with body {"firstname":"eric","name":"taix"}
[2014-03-06 12:58:15.500] DEBUG http: R5: POST data on http://127.0.0.1:7474/db/data/node with body 
[2014-03-06 12:58:15.682] DEBUG http: R2: Received data in 284ms with status 201: [{
  "extensions" : {
  },
  "outgoing_relationships" : "http://127.0.0.1:7474/db/data/node/20/relationships/out",
  "labels" : "http://127.0.0.1:7474/db/data/node/20/labels",
  "all_typed_relationships" : "http://127.0.0.1:7474/db/data/node/20/relationships/all/{-list|&|types}",
  "traverse" : "http://127.0.0.1:7474/db/data/node/20/traverse/{returnType}",
  "property" : "http://127.0.0.1:7474/db/data/node/20/properties/{key}",
  "self" : "http://127.0.0.1:7474/db/data/node/20",
  "properties" : "http://127.0.0.1:7474/db/data/node/20/properties",
  "outgoing_typed_relationships" : "http://127.0.0.1:7474/db/data/node/20/relationships/out/{-list|&|types}",
  "incoming_relationships" : "http://127.0.0.1:7474/db/data/node/20/relationships/in",
  "create_relationship" : "http://127.0.0.1:7474/db/data/node/20/relationships",
  "paged_traverse" : "http://127.0.0.1:7474/db/data/node/20/paged/traverse/{returnType}{?pageSize,leaseTime}",
  "all_relationships" : "http://127.0.0.1:7474/db/data/node/20/relationships/all",
  "incoming_typed_relationships" : "http://127.0.0.1:7474/db/data/node/20/relationships/in/{-list|&|types}",
  "data" : {
    "name" : "taix",
    "firstname" : "eric"
  }
}]
[2014-03-06 12:58:15.683] DEBUG http: R4: Received data in 282ms with status 201: [{
  "extensions" : {
  },
  "outgoing_relationships" : "http://127.0.0.1:7474/db/data/node/19/relationships/out",
  "labels" : "http://127.0.0.1:7474/db/data/node/19/labels",
  "all_typed_relationships" : "http://127.0.0.1:7474/db/data/node/19/relationships/all/{-list|&|types}",
  "traverse" : "http://127.0.0.1:7474/db/data/node/19/traverse/{returnType}",
  "property" : "http://127.0.0.1:7474/db/data/node/19/properties/{key}",
  "self" : "http://127.0.0.1:7474/db/data/node/19",
  "properties" : "http://127.0.0.1:7474/db/data/node/19/properties",
  "outgoing_typed_relationships" : "http://127.0.0.1:7474/db/data/node/19/relationships/out/{-list|&|types}",
  "incoming_relationships" : "http://127.0.0.1:7474/db/data/node/19/relationships/in",
  "create_relationship" : "http://127.0.0.1:7474/db/data/node/19/relationships",
  "paged_traverse" : "http://127.0.0.1:7474/db/data/node/19/paged/traverse/{returnType}{?pageSize,leaseTime}",
  "all_relationships" : "http://127.0.0.1:7474/db/data/node/19/relationships/all",
  "incoming_typed_relationships" : "http://127.0.0.1:7474/db/data/node/19/relationships/in/{-list|&|types}",
  "data" : {
    "name" : "taix",
    "firstname" : "eric"
  }
}]
[2014-03-06 12:58:15.688] DEBUG http: R3: Received data in 290ms with status 201: [{
  "extensions" : {
  },
  "outgoing_relationships" : "http://127.0.0.1:7474/db/data/node/18/relationships/out",
  "labels" : "http://127.0.0.1:7474/db/data/node/18/labels",
  "all_typed_relationships" : "http://127.0.0.1:7474/db/data/node/18/relationships/all/{-list|&|types}",
  "traverse" : "http://127.0.0.1:7474/db/data/node/18/traverse/{returnType}",
  "property" : "http://127.0.0.1:7474/db/data/node/18/properties/{key}",
  "self" : "http://127.0.0.1:7474/db/data/node/18",
  "properties" : "http://127.0.0.1:7474/db/data/node/18/properties",
  "outgoing_typed_relationships" : "http://127.0.0.1:7474/db/data/node/18/relationships/out/{-list|&|types}",
  "incoming_relationships" : "http://127.0.0.1:7474/db/data/node/18/relationships/in",
  "create_relationship" : "http://127.0.0.1:7474/db/data/node/18/relationships",
  "paged_traverse" : "http://127.0.0.1:7474/db/data/node/18/paged/traverse/{returnType}{?pageSize,leaseTime}",
  "all_relationships" : "http://127.0.0.1:7474/db/data/node/18/relationships/all",
  "incoming_typed_relationships" : "http://127.0.0.1:7474/db/data/node/18/relationships/in/{-list|&|types}",
  "data" : {
    "name" : "taix2",
    "firstname" : "eric2"
  }
}]
[2014-03-06 12:58:15.689] DEBUG http: R5: Received data in 188ms with status 201: [{
  "extensions" : {
  },
  "outgoing_relationships" : "http://127.0.0.1:7474/db/data/node/21/relationships/out",
  "labels" : "http://127.0.0.1:7474/db/data/node/21/labels",
  "all_typed_relationships" : "http://127.0.0.1:7474/db/data/node/21/relationships/all/{-list|&|types}",
  "traverse" : "http://127.0.0.1:7474/db/data/node/21/traverse/{returnType}",
  "property" : "http://127.0.0.1:7474/db/data/node/21/properties/{key}",
  "self" : "http://127.0.0.1:7474/db/data/node/21",
  "properties" : "http://127.0.0.1:7474/db/data/node/21/properties",
  "outgoing_typed_relationships" : "http://127.0.0.1:7474/db/data/node/21/relationships/out/{-list|&|types}",
  "incoming_relationships" : "http://127.0.0.1:7474/db/data/node/21/relationships/in",
  "create_relationship" : "http://127.0.0.1:7474/db/data/node/21/relationships",
  "paged_traverse" : "http://127.0.0.1:7474/db/data/node/21/paged/traverse/{returnType}{?pageSize,leaseTime}",
  "all_relationships" : "http://127.0.0.1:7474/db/data/node/21/relationships/all",
  "incoming_typed_relationships" : "http://127.0.0.1:7474/db/data/node/21/relationships/in/{-list|&|types}",
  "data" : {
  }
}]
[2014-03-06 12:58:15.689] DEBUG http: R1: Received data in 309ms with status 201: [{
  "extensions" : {
  },
  "outgoing_relationships" : "http://127.0.0.1:7474/db/data/node/22/relationships/out",
  "labels" : "http://127.0.0.1:7474/db/data/node/22/labels",
  "all_typed_relationships" : "http://127.0.0.1:7474/db/data/node/22/relationships/all/{-list|&|types}",
  "traverse" : "http://127.0.0.1:7474/db/data/node/22/traverse/{returnType}",
  "property" : "http://127.0.0.1:7474/db/data/node/22/properties/{key}",
  "self" : "http://127.0.0.1:7474/db/data/node/22",
  "properties" : "http://127.0.0.1:7474/db/data/node/22/properties",
  "outgoing_typed_relationships" : "http://127.0.0.1:7474/db/data/node/22/relationships/out/{-list|&|types}",
  "incoming_relationships" : "http://127.0.0.1:7474/db/data/node/22/relationships/in",
  "create_relationship" : "http://127.0.0.1:7474/db/data/node/22/relationships",
  "paged_traverse" : "http://127.0.0.1:7474/db/data/node/22/paged/traverse/{returnType}{?pageSize,leaseTime}",
  "all_relationships" : "http://127.0.0.1:7474/db/data/node/22/relationships/all",
  "incoming_typed_relationships" : "http://127.0.0.1:7474/db/data/node/22/relationships/in/{-list|&|types}",
  "data" : {
    "name" : "taix",
    "firstname" : "eric"
  }
}]
[2014-03-06 12:58:15.699] DEBUG http: R6: POST data on http://127.0.0.1:7474/db/data/node with body {"name":"Eric Taix","birthday":"1968/11/11"}
[2014-03-06 12:58:15.712] DEBUG http: R6: Received data in 13ms with status 201: [{
  "extensions" : {
  },
  "outgoing_relationships" : "http://127.0.0.1:7474/db/data/node/23/relationships/out",
  "labels" : "http://127.0.0.1:7474/db/data/node/23/labels",
  "all_typed_relationships" : "http://127.0.0.1:7474/db/data/node/23/relationships/all/{-list|&|types}",
  "traverse" : "http://127.0.0.1:7474/db/data/node/23/traverse/{returnType}",
  "property" : "http://127.0.0.1:7474/db/data/node/23/properties/{key}",
  "self" : "http://127.0.0.1:7474/db/data/node/23",
  "properties" : "http://127.0.0.1:7474/db/data/node/23/properties",
  "outgoing_typed_relationships" : "http://127.0.0.1:7474/db/data/node/23/relationships/out/{-list|&|types}",
  "incoming_relationships" : "http://127.0.0.1:7474/db/data/node/23/relationships/in",
  "create_relationship" : "http://127.0.0.1:7474/db/data/node/23/relationships",
  "paged_traverse" : "http://127.0.0.1:7474/db/data/node/23/paged/traverse/{returnType}{?pageSize,leaseTime}",
  "all_relationships" : "http://127.0.0.1:7474/db/data/node/23/relationships/all",
  "incoming_typed_relationships" : "http://127.0.0.1:7474/db/data/node/23/relationships/in/{-list|&|types}",
  "data" : {
    "birthday" : "1968/11/11",
    "name" : "Eric Taix"
  }
}]
[2014-03-06 12:58:15.715] DEBUG http: R7: GET data on http://127.0.0.1:7474/db/data/node/199 with body 
[2014-03-06 12:58:15.728] DEBUG http: R7: Received data in 14ms with status 404: [{
  "message" : "Cannot find node with id [199] in database.",
  "exception" : "NodeNotFoundException",
  "fullname" : "org.neo4j.server.rest.web.NodeNotFoundException",
  "stacktrace" : [ "org.neo4j.server.rest.web.DatabaseActions.node(DatabaseActions.java:183)", "org.neo4j.server.rest.web.DatabaseActions.getNode(DatabaseActions.java:228)", "org.neo4j.server.rest.web.RestfulGraphDatabase.getNode(RestfulGraphDatabase.java:265)", "java.lang.reflect.Method.invoke(Method.java:601)", "org.neo4j.server.rest.transactional.TransactionalRequestDispatcher.dispatch(TransactionalRequestDispatcher.java:139)", "org.neo4j.server.rest.security.SecurityFilter.doFilter(SecurityFilter.java:112)", "java.lang.Thread.run(Thread.java:722)" ]
}]
Uncaught Error: Instance of 'RestException'
Unhandled exception:
Instance of 'RestException'
#0      _rootHandleUncaughtError.<anonymous closure>.<anonymous closure> (dart:async/zone.dart:677)
#1      _asyncRunCallback (dart:async/schedule_microtask.dart:18)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:21)
#3      _createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:11)
#4      _Timer._createTimerHandler._handleTimeout (timer_impl.dart:151)
#5      _Timer._createTimerHandler._handleTimeout (timer_impl.dart:159)
#6      _Timer._createTimerHandler._handleTimeout (timer_impl.dart:159)
#7      _Timer._createTimerHandler.<anonymous closure> (timer_impl.dart:166)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:93)

```

I just replaced id 199 with 1 to get the tests to run on my machine and then the tests ran just fine:

```
#REST Api compatibility check list  





This check list is based on the [REST api documentation](http://docs.neo4j.org/chunked/snapshot/rest-api.html) of Neo4j 2.0 snapshot  

This file is generated by automated unit-tests  







##Results  



![Failed](./failed.png) Transactionnal : 20.1.1. Begin a transaction
  (Not implemented)

![Failed](./failed.png) Transactionnal : 20.1.2. Execute statements in an open transaction
  (Not implemented)

![Failed](./failed.png) Transactionnal : 20.1.3. Execute statements in an open transaction in REST format for the return
  (Not implemented)

![Failed](./failed.png) Transactionnal : 20.1.4. Reset transaction timeout of an open transaction
  (Not implemented)

![Failed](./failed.png) Transactionnal : 20.1.5. Commit an open transaction
  (Not implemented)

![Failed](./failed.png) Transactionnal : 20.1.6. Rollback an open transaction
  (Not implemented)

![Failed](./failed.png) Transactionnal : 20.1.7. Begin and commit a transaction in one request
  (Not implemented)

![Failed](./failed.png) Transactionnal : 20.1.8. Return results in graph format
  (Not implemented)

![Failed](./failed.png) Transactionnal : 20.1.9. Handling errors
  (Not implemented)

![Failed](./failed.png) Service root : 20.2.1. Get service root
  (Not implemented)

![Failed](./failed.png) Streaming : 20.3. Streaming
  (Not implemented)

![Failed](./failed.png) Cypher queries : 20.4.1. Use parameters
  (Not implemented)

![Failed](./failed.png) Cypher queries : 20.4.2. Create a node
  (Not implemented)

![Failed](./failed.png) Cypher queries : 20.4.3. Create a node with multiple properties
  (Not implemented)

![Failed](./failed.png) Cypher queries : 20.4.4. Create mutiple nodes with properties
  (Not implemented)

![Failed](./failed.png) Cypher queries : 20.4.5. Set all properties on a node using Cypher
  (Not implemented)

![Failed](./failed.png) Cypher queries : 20.4.6. Send a query
  (Not implemented)

![Failed](./failed.png) Cypher queries : 20.4.7. Return paths
  (Not implemented)

![Failed](./failed.png) Cypher queries : 20.4.8. Nested results
  (Not implemented)

![Failed](./failed.png) Cypher queries : 20.4.9. Retrieve query metadata
  (Not implemented)

![Failed](./failed.png) Cypher queries : 20.4.10. Errors
  (Not implemented)

![Failed](./failed.png) Property values : 20.5.1. Arrays
  (Not implemented)

![Failed](./failed.png) Property values : 20.5.2. Property keys
  (Not implemented)

![Failed](./failed.png) Property values : 20.5.3. List all property keys
  (Not implemented)

![Passed](./passed.png) Nodes : 20.6.1. Create node

![Passed](./passed.png) Nodes : 20.6.2. Create node with properties

![Passed](./passed.png) Nodes : 20.6.3. Get node

![Passed](./passed.png) Nodes : 20.6.4. Get non-existent node

![Passed](./passed.png) Nodes : 20.6.5. Delete node

![Passed](./passed.png) Nodes : 20.6.6. Nodes with relationships cannot be deleted

![Failed](./failed.png) Relationships : 20.7.1. Get Relationship by ID
  (Not yet implemented)

![Passed](./passed.png) Relationships : 20.7.2. Create relationship

![Passed](./passed.png) Relationships : 20.7.3. Create a relationship with properties

![Passed](./passed.png) Relationships : 20.7.4. Delete relationship

![Passed](./passed.png) Relationships : 20.7.5. Get all properties on a relationship

![Passed](./passed.png) Relationships : 20.7.6. Set all properties on a relationship

![Passed](./passed.png) Relationships : 20.7.7. Get single property on a relationship

![Passed](./passed.png) Relationships : 20.7.8. Set single property on a relationship

![Passed](./passed.png) Relationships : 20.7.9. Get all relationships

![Passed](./passed.png) Relationships : 20.7.10. Get incoming relationships

![Passed](./passed.png) Relationships : 20.7.11. Get outgoing relationships

![Passed](./passed.png) Relationships : 20.7.12. Get typed relationships

![Passed](./passed.png) Relationships : 20.7.13. Get relationships on a node without relationships

![Passed](./passed.png) Relationship types : 20.8.1. Get relationship types

![Passed](./passed.png) Node properties : 20.9.1. Set property on node

![Passed](./passed.png) Node properties : 20.9.2. Update node properties

![Passed](./passed.png) Node properties : 20.9.3. Get properties for node

![Passed](./passed.png) Node properties : 20.9.4. Property values can not be null

![Passed](./passed.png) Node properties : 20.9.5. Property values can not be nested

![Passed](./passed.png) Node properties : 20.9.6. Delete all properties from node

![Passed](./passed.png) Node properties : 20.9.7. Delete a named property from a node

![Passed](./passed.png) Node labels : 20.11.1. Adding a label to a node

![Passed](./passed.png) Node labels : 20.11.2. Adding multiple labels to a node

![Passed](./passed.png) Node labels : 20.11.3. Adding a label with an invalid name

![Passed](./passed.png) Node labels : 20.11.4. Replacing labels on a node

![Passed](./passed.png) Node labels : 20.11.5. Removing a label from a node

![Passed](./passed.png) Node labels : 20.11.6. Listing labels for a node

![Failed](./failed.png) Node labels : 20.11.7. Get all nodes with a label
  (Can't be implemented: wait for Neo4J answer)

![Failed](./failed.png) Node labels : 20.11.8. Get nodes by label and property
  (Can't be implemented: wait for Neo4J answer)

![Failed](./failed.png) Node labels : 20.11.9. List all labels
  (Can't be implemented: wait for Neo4J answer)

![Failed](./failed.png) Indexing : 20.12.1. Create index
  (Not implemented)

![Failed](./failed.png) Indexing : 20.12.2. List indexes for a label
  (Not implemented)

![Failed](./failed.png) Indexing : 20.12.3. Drop index
  (Not implemented)

![Failed](./failed.png) Constraints : 20.13.1. Create uniqueness constraint
  (Not implemented)

![Failed](./failed.png) Constraints : 20.13.2. Get a specific uniqueness constraint
  (Not implemented)

![Failed](./failed.png) Constraints : 20.13.3. Get all uniqueness constraints for a label
  (Not implemented)

![Failed](./failed.png) Constraints : 20.13.4. Get all constraints for a label
  (Not implemented)

![Failed](./failed.png) Constraints : 20.13.5. Get all constraints
  (Not implemented)

![Failed](./failed.png) Constraints : 20.13.6. Drop constraint
  (Not implemented)

![Failed](./failed.png) Traversals : 20.14.1. Traversal using a return filter
  (Not implemented)

![Failed](./failed.png) Traversals : 20.14.2. Return relationships from a traversal
  (Not implemented)

![Failed](./failed.png) Traversals : 20.14.3. Return paths from a traversal
  (Not implemented)

![Failed](./failed.png) Traversals : 20.14.4. Traversal returning nodes below a certain depth
  (Not implemented)

![Failed](./failed.png) Traversals : 20.14.5. Creating a paged traverser
  (Not implemented)

![Failed](./failed.png) Traversals : 20.14.6. Paging through the results of a paged traverser
  (Not implemented)

![Failed](./failed.png) Traversals : 20.14.7. Paged traverser page size
  (Not implemented)

![Failed](./failed.png) Traversals : 20.14.8. Paged traverser timeout
  (Not implemented)

![Failed](./failed.png) Graph Algorithms : 20.15.1. Find all shortest paths
  (Not implemented)

![Failed](./failed.png) Graph Algorithms : 20.15.2. Find one of the shortest paths
  (Not implemented)

![Failed](./failed.png) Graph Algorithms : 20.15.3. Execute a Dijkstra algorithm and get a single path
  (Not implemented)

![Failed](./failed.png) Graph Algorithms : 20.15.4. Execute a Dijkstra algorithm with equal weights on relationships
  (Not implemented)

![Failed](./failed.png) Graph Algorithms : 20.15.5. Execute a Dijkstra algorithm and get multiple paths
  (Not implemented)

![Passed](./passed.png) Batch operations : 20.16.1. Execute multiple operations in batch

![Failed](./failed.png) Batch operations : 20.16.2. Refer to items created earlier in the same batch job
  (Not implemented)

![Failed](./failed.png) Batch operations : 20.16.3. Execute multiple operations in batch streaming
  (Not implemented)

![Passed](./passed.png) 20.10.1. Update relationship properties

![Passed](./passed.png) 20.10.2. Remove properties from a relationship

![Passed](./passed.png) 20.10.3. Remove property from a relationship

![Passed](./passed.png) 20.10.4. Remove non-existent property from a relationship

![Passed](./passed.png) 20.10.5. Remove properties from a non-existing relationship

![Passed](./passed.png) 20.10.6. Remove property from a non-existing relationship


39 PASSED, 52 FAILED, 0 ERRORS
```

**Comment by eric-taix** [comment]
Thanks for your report: I'll check this issue soon!
I know some ids are hardcoded and I have to find a nice way to populate the database with stable values (especially ids). If you know how to, just let me know. Also all pullrequest are really welcome
